global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'liberty'
    metrics_path: /metrics
    static_configs:
      - targets:
          - '192.168.68.88:9080'
          - '192.168.68.86:9080'
        labels:
          environment: 'development'

  - job_name: 'node'
    static_configs:
      - targets:
          - '192.168.68.82:9100'
          - '192.168.68.88:9100'
          - '192.168.68.86:9100'

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.68.206:8080']
