---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Liberty
  ansible.builtin.systemd:
    name: "liberty-{{ liberty_server_name }}"
    state: restarted
  async: 360
  poll: 10
  register: liberty_restart

- name: Verify Liberty restart
  ansible.builtin.debug:
    msg: "Liberty restart completed"
  when: liberty_restart is defined
