---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: middleware-automation-platform

resources:
  - maven-cache-pvc.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      environment: development
    includeSelectors: false
